language: go

env:
  - GO111MODULE=on

go:
  - "1.11.x"

# Fix tests so they can run on travis eventually, right now travis is too slow

install: 'echo "one day I should fix this to run the tests slower"'


